package com.belgieyt.morefeatures.init;

import com.belgieyt.morefeatures.MoreFeatures;
import com.belgieyt.morefeatures.*;
import com.belgieyt.morefeatures.blocks.*;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.*;
import net.minecraft.particles.ParticleTypes;
import net.minecraft.potion.Effects;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import javax.annotation.Nullable;
import java.util.Collection;
import java.util.function.Supplier;

@Mod.EventBusSubscriber(modid = MoreFeatures.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class BlockInit {



    public static final  DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, MoreFeatures.MOD_ID);

    // Blocks
    public static final RegistryObject<Block> STRAWBERRY_BUSH = r("strawberry_bush", () -> new StrawberryBush(AbstractBlock.Properties.from(Blocks.SWEET_BERRY_BUSH)));
    public static final RegistryObject<Block> MILK_CUP = r("milkcup_flower", () -> new FlowerBlock( Effects.HASTE, 10,AbstractBlock.Properties.create(Material.PLANTS).doesNotBlockMovement().zeroHardnessAndResistance().sound(SoundType.PLANT)));
    public static final RegistryObject<Block> MAGENTA_LEAVES = r("magenta_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> BLUEBERRY_BUSH = r("blueberry_bush", () -> new BlueberryBush(AbstractBlock.Properties.from(Blocks.SWEET_BERRY_BUSH)));
    public static final RegistryObject<Block> KIWI_VINES = r("kiwi_vines", () -> new KiwiVines(AbstractBlock.Properties.from(Blocks.SWEET_BERRY_BUSH)));
    public static final RegistryObject<Block> BLACKBERRY_BUSH = r("blackberry_bush", () -> new BlackberryBush(AbstractBlock.Properties.from(Blocks.SWEET_BERRY_BUSH)));
    public static final RegistryObject<TorchBlock> DEVIL_TORCH = r("devil_torch", () -> new TorchBlock(AbstractBlock.Properties.from(Blocks.TORCH).doesNotBlockMovement().zeroHardnessAndResistance().setLightLevel((p_235470_0_) -> {
        return 15;}).sound(SoundType.NETHERITE), ParticleTypes.CRIMSON_SPORE));
    public static final RegistryObject<WallTorchBlock> DEVIL_WALL_TORCH = r("devil_wall_torch",() -> new WallTorchBlock(AbstractBlock.Properties.from(Blocks.WALL_TORCH).doesNotBlockMovement().zeroHardnessAndResistance().setLightLevel((p_235469_0_) -> {
        return 15;
    }).sound(SoundType.NETHERITE).lootFrom(DEVIL_TORCH.get()), ParticleTypes.CRIMSON_SPORE));
    public static final RegistryObject<Block> BLACK_PLANKS = r("black_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> BLACK_PLANK_STAIRS = r("black_plank_stairs", () -> new StairsBlock(BLACK_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(BLACK_PLANKS.get())));
    public static final RegistryObject<SlabBlock> BLACK_PLANK_SLAB = r("black_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(BLACK_PLANKS.get())));
    public static final RegistryObject<DoorBlock> BLACK_PLANK_DOOR = r("black_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> BLACK_PLANK_TRAPDOOR = r("black_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> WHITE_PLANKS = r("white_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> WHITE_PLANK_STAIRS = r("white_plank_stairs", () -> new StairsBlock(WHITE_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(WHITE_PLANKS.get())));
    public static final RegistryObject<SlabBlock> WHITE_PLANK_SLAB = r("white_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(WHITE_PLANKS.get())));
    public static final RegistryObject<DoorBlock> WHITE_PLANK_DOOR = r("white_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> WHITE_PLANK_TRAPDOOR = r("white_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> RED_PLANKS = r("red_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> RED_PLANK_STAIRS = r("red_plank_stairs", () -> new StairsBlock(RED_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(RED_PLANKS.get())));
    public static final RegistryObject<SlabBlock> RED_PLANK_SLAB = r("red_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(RED_PLANKS.get())));
    public static final RegistryObject<DoorBlock> RED_PLANK_DOOR = r("red_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> RED_PLANK_TRAPDOOR = r("red_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> BLUE_PLANKS = r("blue_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> BLUE_PLANK_STAIRS = r("blue_plank_stairs", () -> new StairsBlock(BLUE_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(BLUE_PLANKS.get())));
    public static final RegistryObject<SlabBlock> BLUE_PLANK_SLAB = r("blue_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(BLUE_PLANKS.get())));
    public static final RegistryObject<DoorBlock> BLUE_PLANK_DOOR = r("blue_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> BLUE_PLANK_TRAPDOOR = r("blue_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> GRAY_PLANKS = r("gray_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> GRAY_PLANK_STAIRS = r("gray_plank_stairs", () -> new StairsBlock(GRAY_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(GRAY_PLANKS.get())));
    public static final RegistryObject<SlabBlock> GRAY_PLANK_SLAB = r("gray_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(GRAY_PLANKS.get())));
    public static final RegistryObject<DoorBlock> GRAY_PLANK_DOOR = r("gray_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> GRAY_PLANK_TRAPDOOR = r("gray_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> PINK_PLANKS = r("pink_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> PINK_PLANK_STAIRS = r("pink_plank_stairs", () -> new StairsBlock(PINK_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(PINK_PLANKS.get())));
    public static final RegistryObject<SlabBlock> PINK_PLANK_SLAB = r("pink_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(PINK_PLANKS.get())));
    public static final RegistryObject<DoorBlock> PINK_PLANK_DOOR = r("pink_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> PINK_PLANK_TRAPDOOR = r("pink_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> ORANGE_PLANKS = r("orange_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> ORANGE_PLANK_STAIRS = r("orange_plank_stairs", () -> new StairsBlock(ORANGE_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(ORANGE_PLANKS.get())));
    public static final RegistryObject<SlabBlock> ORANGE_PLANK_SLAB = r("orange_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(ORANGE_PLANKS.get())));
    public static final RegistryObject<DoorBlock> ORANGE_PLANK_DOOR = r("orange_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> ORANGE_PLANK_TRAPDOOR = r("orange_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> LIME_PLANKS = r("lime_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> LIME_PLANK_STAIRS = r("lime_plank_stairs", () -> new StairsBlock(LIME_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(LIME_PLANKS.get())));
    public static final RegistryObject<SlabBlock> LIME_PLANK_SLAB = r("lime_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(LIME_PLANKS.get())));
    public static final RegistryObject<DoorBlock> LIME_PLANK_DOOR = r("lime_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> LIME_PLANK_TRAPDOOR = r("lime_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<StairsBlock> DIRT_STAIRS = r("dirt_stairs", () -> new StairsBlock(Blocks.DIRT.getDefaultState(), AbstractBlock.Properties.from(Blocks.DIRT)));
    public static final RegistryObject<SlabBlock> DIRT_SLAB = r("dirt_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.DIRT)));
    public static final RegistryObject<WallBlock> STONE_WALL = r("stone_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<WallBlock> SMOOTH_STONE_WALL = r("smooth_stone_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<WallBlock> QUARTZ_WALL = r("quartz_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<WallBlock> PRISMARINE_BRICK_WALL = r("prismarine_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<WallBlock> DARK_PRISMARINE_WALL = r("dark_prismarine_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<FenceBlock> OAK_LOG_FENCE = r("oak_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> SPRUCE_LOG_FENCE = r("spruce_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> BIRCH_LOG_FENCE = r("birch_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> JUNGLE_LOG_FENCE = r("jungle_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> ACACIA_LOG_FENCE = r("acacia_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> DARK_OAK_LOG_FENCE = r("dark_oak_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> CRIMSON_LOG_FENCE = r("crimson_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<FenceBlock> WARPED_LOG_FENCE = r("warped_log_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<Block> BROWN_PLANKS = r("brown_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> BROWN_PLANK_STAIRS = r("brown_plank_stairs", () -> new StairsBlock(BROWN_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(BROWN_PLANKS.get())));
    public static final RegistryObject<SlabBlock> BROWN_PLANK_SLAB = r("brown_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(BROWN_PLANKS.get())));
    public static final RegistryObject<DoorBlock> BROWN_PLANK_DOOR = r("brown_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> BROWN_PLANK_TRAPDOOR = r("brown_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> YELLOW_PLANKS = r("yellow_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> YELLOW_PLANK_STAIRS = r("yellow_plank_stairs", () -> new StairsBlock(YELLOW_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(YELLOW_PLANKS.get())));
    public static final RegistryObject<SlabBlock> YELLOW_PLANK_SLAB = r("yellow_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(YELLOW_PLANKS.get())));
    public static final RegistryObject<DoorBlock> YELLOW_PLANK_DOOR = r("yellow_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> YELLOW_PLANK_TRAPDOOR = r("yellow_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> LIGHT_GRAY_PLANKS = r("light_gray_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> LIGHT_GRAY_PLANK_STAIRS = r("light_gray_plank_stairs", () -> new StairsBlock(LIGHT_GRAY_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(LIGHT_GRAY_PLANKS.get())));
    public static final RegistryObject<SlabBlock> LIGHT_GRAY_PLANK_SLAB = r("light_gray_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(LIGHT_GRAY_PLANKS.get())));
    public static final RegistryObject<DoorBlock> LIGHT_GRAY_PLANK_DOOR = r("light_gray_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> LIGHT_GRAY_PLANK_TRAPDOOR = r("light_gray_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> PURPLE_PLANKS = r("purple_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> PURPLE_PLANK_STAIRS = r("purple_plank_stairs", () -> new StairsBlock(PURPLE_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(PURPLE_PLANKS.get())));
    public static final RegistryObject<SlabBlock> PURPLE_PLANK_SLAB = r("purple_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(PURPLE_PLANKS.get())));
    public static final RegistryObject<DoorBlock> PURPLE_PLANK_DOOR = r("purple_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> PURPLE_PLANK_TRAPDOOR = r("purple_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<Block> CYAN_PLANKS = r("cyan_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> CYAN_PLANK_STAIRS = r("cyan_plank_stairs", () -> new StairsBlock(CYAN_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(CYAN_PLANKS.get())));
    public static final RegistryObject<SlabBlock> CYAN_PLANK_SLAB = r("cyan_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(CYAN_PLANKS.get())));
    public static final RegistryObject<DoorBlock> CYAN_PLANK_DOOR = r("cyan_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> CYAN_PLANK_TRAPDOOR = r("cyan_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<FenceGateBlock> OAK_LOG_FENCE_GATE = r("oak_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> SPRUCE_LOG_FENCE_GATE = r("spruce_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> BIRCH_LOG_FENCE_GATE = r("birch_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> JUNGLE_LOG_FENCE_GATE = r("jungle_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> ACACIA_LOG_FENCE_GATE = r("acacia_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> DARK_OAK_LOG_FENCE_GATE = r("dark_oak_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> CRIMSON_LOG_FENCE_GATE = r("crimson_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> WARPED_LOG_FENCE_GATE = r("warped_log_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceGateBlock> BLACK_PLANK_FENCE_GATE = r("black_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> BLACK_PLANK_FENCE = r("black_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> BLACK_PLANK_BUTTON = r("black_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> BLACK_PLANK_PRESSURE_PLATE = r("black_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> YELLOW_PLANK_FENCE_GATE = r("yellow_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> YELLOW_PLANK_FENCE = r("yellow_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> YELLOW_PLANK_BUTTON = r("yellow_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> YELLOW_PLANK_PRESSURE_PLATE = r("yellow_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> BROWN_PLANK_FENCE_GATE = r("brown_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> BROWN_PLANK_FENCE = r("brown_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> BROWN_PLANK_BUTTON = r("brown_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> BROWN_PLANK_PRESSURE_PLATE = r("brown_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> WHITE_PLANK_FENCE_GATE = r("white_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> WHITE_PLANK_FENCE = r("white_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> WHITE_PLANK_BUTTON = r("white_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> WHITE_PLANK_PRESSURE_PLATE = r("white_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> LIME_PLANK_FENCE_GATE = r("lime_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> LIME_PLANK_FENCE = r("lime_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> LIME_PLANK_BUTTON = r("lime_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> LIME_PLANK_PRESSURE_PLATE = r("lime_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<Block> MAGENTA_PLANKS = r("magenta_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> MAGENTA_PLANK_STAIRS = r("magenta_plank_stairs", () -> new StairsBlock(MAGENTA_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(MAGENTA_PLANKS.get())));
    public static final RegistryObject<SlabBlock> MAGENTA_PLANK_SLAB = r("magenta_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(MAGENTA_PLANKS.get())));
    public static final RegistryObject<DoorBlock> MAGENTA_PLANK_DOOR = r("magenta_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> MAGENTA_PLANK_TRAPDOOR = r("magenta_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<FenceGateBlock> RED_PLANK_FENCE_GATE = r("red_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> RED_PLANK_FENCE = r("red_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> RED_PLANK_BUTTON = r("red_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> RED_PLANK_PRESSURE_PLATE = r("red_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> BLUE_PLANK_FENCE_GATE = r("blue_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> BLUE_PLANK_FENCE = r("blue_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> BLUE_PLANK_BUTTON = r("blue_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> BLUE_PLANK_PRESSURE_PLATE = r("blue_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> GRAY_PLANK_FENCE_GATE = r("gray_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> GRAY_PLANK_FENCE = r("gray_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> GRAY_PLANK_BUTTON = r("gray_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> GRAY_PLANK_PRESSURE_PLATE = r("gray_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> PINK_PLANK_FENCE_GATE = r("pink_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> PINK_PLANK_FENCE = r("pink_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> PINK_PLANK_BUTTON = r("pink_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> PINK_PLANK_PRESSURE_PLATE = r("pink_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> ORANGE_PLANK_FENCE_GATE = r("orange_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> ORANGE_PLANK_FENCE = r("orange_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> ORANGE_PLANK_BUTTON = r("orange_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> ORANGE_PLANK_PRESSURE_PLATE = r("orange_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> LIGHT_GRAY_PLANK_FENCE_GATE = r("light_gray_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> LIGHT_GRAY_PLANK_FENCE = r("light_gray_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> LIGHT_GRAY_PLANK_BUTTON = r("light_gray_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> LIGHT_GRAY_PLANK_PRESSURE_PLATE = r("light_gray_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> PURPLE_PLANK_FENCE_GATE = r("purple_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> PURPLE_PLANK_FENCE = r("purple_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> PURPLE_PLANK_BUTTON = r("purple_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> PURPLE_PLANK_PRESSURE_PLATE = r("purple_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> CYAN_PLANK_FENCE_GATE = r("cyan_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> CYAN_PLANK_FENCE = r("cyan_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> CYAN_PLANK_BUTTON = r("cyan_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> CYAN_PLANK_PRESSURE_PLATE = r("cyan_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<Block> GREEN_PLANKS = r("green_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> GREEN_PLANK_STAIRS = r("green_plank_stairs", () -> new StairsBlock(GREEN_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(GREEN_PLANKS.get())));
    public static final RegistryObject<SlabBlock> GREEN_PLANK_SLAB = r("green_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(GREEN_PLANKS.get())));
    public static final RegistryObject<DoorBlock> GREEN_PLANK_DOOR = r("green_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> GREEN_PLANK_TRAPDOOR = r("green_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<FenceGateBlock> GREEN_PLANK_FENCE_GATE = r("green_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> GREEN_PLANK_FENCE = r("green_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> GREEN_PLANK_BUTTON = r("green_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> GREEN_PLANK_PRESSURE_PLATE = r("green_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<FenceGateBlock> MAGENTA_PLANK_FENCE_GATE = r("magenta_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> MAGENTA_PLANK_FENCE = r("magenta_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> MAGENTA_PLANK_BUTTON = r("magenta_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> MAGENTA_PLANK_PRESSURE_PLATE = r("magenta_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<Block> LIGHT_BLUE_PLANKS = r("light_blue_planks", () -> new Block(AbstractBlock.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<StairsBlock> LIGHT_BLUE_PLANK_STAIRS = r("light_blue_plank_stairs", () -> new StairsBlock(GREEN_PLANKS.get().getDefaultState(), AbstractBlock.Properties.from(GREEN_PLANKS.get())));
    public static final RegistryObject<SlabBlock> LIGHT_BLUE_PLANK_SLAB = r("light_blue_plank_slab", () -> new SlabBlock(AbstractBlock.Properties.from(GREEN_PLANKS.get())));
    public static final RegistryObject<DoorBlock> LIGHT_BLUE_PLANK_DOOR = r("light_blue_plank_door", () -> new DoorBlock(AbstractBlock.Properties.from(Blocks.OAK_DOOR)));
    public static final RegistryObject<TrapDoorBlock> LIGHT_BLUE_PLANK_TRAPDOOR = r("light_blue_plank_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.from(Blocks.OAK_TRAPDOOR)));
    public static final RegistryObject<FenceGateBlock> LIGHT_BLUE_PLANK_FENCE_GATE = r("light_blue_plank_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE_GATE)));
    public static final RegistryObject<FenceBlock> LIGHT_BLUE_PLANK_FENCE = r("light_blue_plank_fence", () -> new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_FENCE)));
    public static final RegistryObject<WoodButtonBlock> LIGHT_BLUE_PLANK_BUTTON = r("light_blue_plank_button", () -> new WoodButtonBlock(AbstractBlock.Properties.from(Blocks.OAK_BUTTON)));
    public static final RegistryObject<PressurePlateBlock> LIGHT_BLUE_PLANK_PRESSURE_PLATE = r("light_blue_plank_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.from(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistryObject<Block> SOULSTONE = r("soulstone",() -> new Block(AbstractBlock.Properties.create(Material.GLASS, MaterialColor.SAND).hardnessAndResistance(0.3F).sound(SoundType.GLASS).setLightLevel((p_235464_0_) -> { return 15; })));
    public static final RegistryObject<Block> SOUL_JACK_O_LANTERN = r("soul_jack_o_lantern",() -> new CarvedPumpkinBlock(AbstractBlock.Properties.create(Material.GOURD, MaterialColor.ADOBE).hardnessAndResistance(1.0F).sound(SoundType.WOOD).setLightLevel((p_235462_0_) -> { return 15; })));
    public static final RegistryObject<AshMushroom> ASH_MUSHROOM = r("ash_mushroom", () -> new AshMushroom(AbstractBlock.Properties.from(Blocks.BROWN_MUSHROOM)));
    public static final RegistryObject<Block> BLACK_CORUPTED_STONE = r("black_corupted_stone", () -> new Block(AbstractBlock.Properties.from(Blocks.END_STONE).setLightLevel((p_235462_0_) -> { return 15;})));
    public static final RegistryObject<Block> DEVIL_JACK_O_LANTERN = r("devil_jack_o_lantern",() -> new CarvedPumpkinBlock(AbstractBlock.Properties.create(Material.GOURD, MaterialColor.ADOBE).hardnessAndResistance(1.0F).sound(SoundType.WOOD).setLightLevel((p_235462_0_) -> { return 15; })));
    public static final RegistryObject<Block> BLUE_BRICKS = r("blue_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> LIME_BRICKS = r("lime_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> BLACK_BRICKS = r("black_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> WHITE_BRICKS = r("white_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> PURPLE_BRICKS = r("purple_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> PINK_BRICKS = r("pink_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> ORANGE_BRICKS = r("orange_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> YELLOW_BRICKS = r("yellow_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> GREEN_BRICKS = r("green_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> LIGHT_BLUE_BRICKS = r("light_blue_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> FLOWER_O_HEALING = r("flower_o_healing", () -> new FlowerOHealing(AbstractBlock.Properties.from(Blocks.WITHER_ROSE)));
    public static final RegistryObject<Block> FLOWER_O_POISON = r("flower_o_poison", () -> new FlowerOPoison(AbstractBlock.Properties.from(Blocks.WITHER_ROSE)));
    public static final RegistryObject<Block> WET_LAVA_SPONGE = r("wet_lava_sponge", () -> new Block(AbstractBlock.Properties.from(Blocks.WET_SPONGE)));
    public static final RegistryObject<Block> LAVA_SPONGE = r("lava_sponge", () -> new LavaSponge(AbstractBlock.Properties.from(Blocks.SPONGE)));
    public static final RegistryObject<Block> BLUE_BRICK_WALL = r("blue_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> GREEN_BRICK_WALL = r("green_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> LIME_BRICK_WALL = r("lime_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> YELLOW_BRICK_WALL = r("yellow_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> ORANGE_BRICK_WALL = r("orange_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> HEAVY_COBBLESTONE = r("heavy_cobblestone", () -> new Block(AbstractBlock.Properties.from(Blocks.COBBLESTONE).sound(SoundType.STONE)));
    public static final RegistryObject<Block> GRAY_BRICKS = r("gray_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> LIGHT_GRAY_BRICKS = r("light_gray_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> BROWN_BRICKS = r("brown_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> MAGENTA_BRICKS = r("magenta_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> CYAN_BRICKS = r("cyan_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> MUSHROOM_HEAD = r("mushroom_head", () -> new MushroomHeadBlock(AbstractBlock.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(1.0F)));
    public static final RegistryObject<Block> BLACK_ITEM_HOLDER = r("black_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> WHITE_ITEM_HOLDER = r("white_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> RED_ITEM_HOLDER = r("red_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> BLUE_ITEM_HOLDER = r("blue_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> YELLOW_ITEM_HOLDER = r("yellow_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> PINK_ITEM_HOLDER = r("pink_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> GREEN_ITEM_HOLDER = r("green_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> GRAY_ITEM_HOLDER = r("gray_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> LIGHT_GRAY_ITEM_HOLDER = r("light_gray_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> LIGHT_BLUE_ITEM_HOLDER = r("light_blue_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> BROWN_ITEM_HOLDER = r("brown_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> CYAN_ITEM_HOLDER = r("cyan_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> LIME_ITEM_HOLDER = r("lime_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> RED_LEAVES = r("red_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> RED_VINE = r("red_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> BLACK_LEAVES = r("black_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> WHITE_LEAVES = r("white_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> BLUE_LEAVES = r("blue_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> LIGHT_BLUE_LEAVES = r("light_blue_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> CYAN_LEAVES = r("cyan_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> YELLOW_LEAVES = r("yellow_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> BROWN_LEAVES = r("brown_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> ORANGE_LEAVES = r("orange_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> LIGHT_GRAY_LEAVES = r("light_gray_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> GRAY_LEAVES = r("gray_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> PINK_LEAVES = r("pink_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> PURPLE_LEAVES = r("purple_leaves", () -> new LeavesBlock(AbstractBlock.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> HEAVY_COBBLESTONE_STAIR = r("heavy_cobblestone_stair", () -> new StairsBlock(BlockInit.HEAVY_COBBLESTONE.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> HEAVY_COBBLESTONE_SLAB = r("heavy_cobblestone_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.COBBLESTONE_SLAB)));
    public static final RegistryObject<Block> LAVENDER = r("lavender", () -> new FlowerBlock(Effects.GLOWING, 5, AbstractBlock.Properties.create(Material.PLANTS).doesNotBlockMovement().zeroHardnessAndResistance().sound(SoundType.PLANT)));
    public static final RegistryObject<Block> ORANGE_ITEM_HOLDER = r("orange_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> MAGENTA_ITEM_HOLDER = r("magenta_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> PURPLE_ITEM_HOLDER = r("purple_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> ORANGE_ROSE_BUSH = r("orange_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> BLACK_ROSE_BUSH = r("black_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> LIGHT_GRAY_ROSE_BUSH = r("light_gray_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> YELLOW_ROSE_BUSH = r("yellow_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> PURPLE_ROSE_BUSH = r("purple_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> WHITE_ROSE_BUSH = r("white_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> BLUE_ROSE_BUSH = r("blue_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> PINK_ROSE_BUSH = r("pink_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> GRAY_ROSE_BUSH = r("gray_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> LIGHT_BLUE_ROSE_BUSH = r("light_blue_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> MAGENTA_ROSE_BUSH = r("magenta_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> CYAN_ROSE_BUSH = r("cyan_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> WHITE_BRICK_WALL = r("white_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> BLACK_BRICK_WALL = r("black_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> GRAY_BRICK_WALL = r("gray_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> LIGHT_GRAY_BRICK_WALL = r("light_gray_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> PURPLE_BRICK_WALL = r("purple_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> PINK_BRICK_WALL = r("pink_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> MAGENTA_BRICK_WALL = r("magenta_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> CYAN_BRICK_WALL = r("cyan_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> BROWN_BRICK_WALL = r("brown_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> LIGHT_BLUE_BRICK_WALL = r("light_blue_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> BROWN_BRICK_SLAB = r("brown_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> BLACK_BRICK_SLAB = r("black_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> WHITE_BRICK_SLAB = r("white_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> GRAY_BRICK_SLAB = r("gray_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> PURPLE_BRICK_SLAB = r("purple_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> PINK_BRICK_SLAB = r("pink_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> MAGENTA_BRICK_SLAB = r("magenta_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> GREEN_BRICK_SLAB = r("green_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> LIME_BRICK_SLAB = r("lime_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> BLUE_BRICK_SLAB = r("blue_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> CYAN_BRICK_SLAB = r("cyan_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> LIGHT_BLUE_BRICK_SLAB = r("light_blue_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> YELLOW_BRICK_SLAB = r("yellow_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> ORANGE_BRICK_SLAB = r("orange_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> LIGHT_GRAY_BRICK_SLAB = r("light_gray_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> BLUE_VINE = r("blue_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> BLACK_BRICK_STAIR = r("black_brick_stair", () -> new StairsBlock(BlockInit.BLACK_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> WHITE_BRICK_STAIR = r("white_brick_stair", () -> new StairsBlock(BlockInit.WHITE_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> GRAY_BRICK_STAIR = r("gray_brick_stair", () -> new StairsBlock(BlockInit.GRAY_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> ADVANCER = r("advancer", ()-> new AdvancerBlock(AbstractBlock.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(3.5F)));
    public static final RegistryObject<Block> WHITE_POLISHED_GLASS = r("white_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> GRAY_POLISHED_GLASS = r("gray_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> RED_POLISHED_GLASS = r("red_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> BLACK_POLISHED_GLASS = r("black_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> CYAN_POLISHED_GLASS = r("cyan_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> BLUE_POLISHED_GLASS = r("blue_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> LIGHT_BLUE_POLISHED_GLASS = r("light_blue_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> PINK_POLISHED_GLASS = r("pink_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> PURPLE_POLISHED_GLASS = r("purple_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> MAGENTA_POLISHED_GLASS = r("magenta_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> GREEN_POLISHED_GLASS = r("green_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> LIME_POLISHED_GLASS = r("lime_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> ORANGE_POLISHED_GLASS = r("orange_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> YELLOW_POLISHED_GLASS = r("yellow_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> BROWN_POLISHED_GLASS = r("brown_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> LIGHT_GRAY_POLISHED_GLASS = r("light_gray_polished_glass", () -> new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()));
    public static final RegistryObject<Block> MOLTEN_OBSIDIAN = r("molten_obsidian", () -> new MoltenObsidian(AbstractBlock.Properties.create(Material.ROCK).hardnessAndResistance(1.0F).sound(SoundType.STONE).notSolid().setLightLevel((p_235462_0_) -> { return 15;})));
    public static final RegistryObject<Block> BLUE_BRICK_STAIR = r("blue_brick_stair", () -> new StairsBlock(BlockInit.BLUE_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> CYAN_BRICK_STAIR = r("cyan_brick_stair", () -> new StairsBlock(BlockInit.CYAN_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> LIGHT_BLUE_BRICK_STAIR = r("light_blue_brick_stair", () -> new StairsBlock(BlockInit.LIGHT_BLUE_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> HEAVY_COBBLESTONE_WALL = r("heavy_cobblestone_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> POTTED_MILK_CUP = r("potted_milk_cup", () -> new FlowerPotBlock(BlockInit.MILK_CUP.get(), AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()));
    public static final RegistryObject<Block> POTTED_LAVENDER = r("potted_lavender", () -> new FlowerPotBlock(LAVENDER.get(), AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()));
    public static final RegistryObject<Block> POTTED_FLOWER_O_HEALING = r("potted_flower_o_healing", () -> new FlowerPotBlock(FLOWER_O_HEALING.get(), AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()));
    public static final RegistryObject<Block> POTTED_FLOWER_O_POISON = r("potted_flower_o_poison", () -> new FlowerPotBlock(FLOWER_O_POISON.get(), AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()));
    public static final RegistryObject<Block> RED_BRICKS = r("red_bricks", () -> new Block(AbstractBlock.Properties.from(Blocks.BRICKS)));
    public static final RegistryObject<Block> PINK_BRICK_STAIR = r("pink_brick_stair", () -> new StairsBlock(BlockInit.PINK_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> PURPLE_BRICK_STAIR = r("purple_brick_stair", () -> new StairsBlock(BlockInit.PURPLE_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> MAGENTA_BRICK_STAIR = r("magenta_brick_stair", () -> new StairsBlock(BlockInit.MAGENTA_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> LIME_BRICK_STAIR = r("lime_brick_stair", () -> new StairsBlock(BlockInit.LIME_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> YELLOW_BRICK_STAIR = r("yellow_brick_stair", () -> new StairsBlock(BlockInit.YELLOW_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> GREEN_BRICK_STAIR = r("green_brick_stair", () -> new StairsBlock(BlockInit.GREEN_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> ORANGE_BRICK_STAIR = r("orange_brick_stair", () -> new StairsBlock(BlockInit.ORANGE_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> BROWN_BRICK_STAIR = r("brown_brick_stair", () -> new StairsBlock(BlockInit.BROWN_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> LIGHT_GRAY_BRICK_STAIR = r("light_gray_brick_stair", () -> new StairsBlock(BlockInit.LIGHT_GRAY_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> RED_BRICK_STAIR = r("red_brick_stair", () -> new StairsBlock(BlockInit.RED_BRICKS.get().getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> RED_BRICK_SLAB = r("red_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.BRICK_SLAB)));
    public static final RegistryObject<Block> RED_BRICK_WALL = r("red_brick_wall", () -> new WallBlock(AbstractBlock.Properties.from(Blocks.BRICK_WALL)));
    public static final RegistryObject<Block> LIGHT_BLUE_VINE = r("light_blue_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> WHITE_VINE = r("white_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> YELLOW_VINE = r("yellow_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> ORANGE_VINE = r("orange_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> BIRCH_ITEM_HOLDER = r("birch_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> OAK_ITEM_HOLDER = r("oak_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> JUNGLE_ITEM_HOLDER = r("jungle_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> CRIMSON_ITEM_HOLDER = r("crimson_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> WARPED_ITEM_HOLDER = r("warped_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> ACACIA_ITEM_HOLDER = r("acacia_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> GREEN_CONCRETE_STAIR = r("green_concrete_stair", () -> new StairsBlock(Blocks.GREEN_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> YELLOW_LEAVE_CARPET = r("yellow_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> BLUE_LEAVE_CARPET = r("blue_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> ORANGE_LEAVE_CARPET = r("orange_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> RED_LEAVE_CARPET = r("red_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> BLACK_LEAVE_CARPET = r("black_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> WHITE_LEAVE_CARPET = r("white_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> GRAY_LEAVE_CARPET = r("gray_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> PINK_LEAVE_CARPET = r("pink_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> PURPLE_LEAVE_CARPET = r("purple_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> MAGENTA_LEAVE_CARPET = r("magenta_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> LIGHT_BLUE_LEAVE_CARPET = r("light_blue_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> LIGHT_GRAY_LEAVE_CARPET = r("light_gray_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> CYAN_LEAVE_CARPET = r("cyan_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> BROWN_LEAVE_CARPET = r("brown_leave_carpet", () -> new CarpetBlock(DyeColor.GREEN,AbstractBlock.Properties.from(Blocks.OAK_LEAVES).sound(SoundType.CROP)));
    public static final RegistryObject<Block> BLACK_VINE = r("black_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> GRAY_VINE = r("gray_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> PINK_VINE = r("pink_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> PURPLE_VINE = r("purple_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> MAGENTA_VINE = r("magenta_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> CYAN_VINE = r("cyan_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> DARK_OAK_ITEM_HOLDER = r("dark_oak_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> SPRUCE_ITEM_HOLDER = r("spruce_item_holder", () ->  new ItemHolderBlock(AbstractBlock.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> BROWN_VINE = r("brown_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> LIGHT_GRAY_VINE = r("light_gray_vine", () -> new VineBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.2F).sound(SoundType.VINE)));
    public static final RegistryObject<Block> BLACK_CONCRETE_STAIR = r("black_concrete_stair", () -> new StairsBlock(Blocks.BLACK_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_STAIR = r("white_concrete_stair", () -> new StairsBlock(Blocks.WHITE_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> GRAY_CONCRETE_STAIR = r("gray_concrete_stair", () -> new StairsBlock(Blocks.GRAY_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> MOON_FLOWER = r("moon_flower", () -> new LadderBlock(AbstractBlock.Properties.create(Material.PLANTS).tickRandomly().hardnessAndResistance(0.2F, 3.0F).sound(SoundType.WOOD).notSolid()));
    public static final RegistryObject<Block> BLUE_CONCRETE_STAIR = r("blue_concrete_stair", () -> new StairsBlock(Blocks.BLUE_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> CYAN_CONCRETE_STAIR = r("cyan_concrete_stair", () -> new StairsBlock(Blocks.CYAN_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_STAIR = r("light_blue_concrete_stair", () -> new StairsBlock(Blocks.LIGHT_BLUE_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> BROWN_ROSE_BUSH = r("brown_rose_bush", () -> new TallFlowerBlock(AbstractBlock.Properties.from(Blocks.ROSE_BUSH)));
    public static final RegistryObject<Block> PINK_CONCRETE_STAIR = r("pink_concrete_stair", () -> new StairsBlock(Blocks.PINK_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> PURPLE_CONCRETE_STAIR = r("purple_concrete_stair", () -> new StairsBlock(Blocks.PURPLE_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> MAGENTA_CONCRETE_STAIR = r("magenta_concrete_stair", () -> new StairsBlock(Blocks.MAGENTA_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> YELLOW_CONCRETE_STAIR = r("yellow_concrete_stair", () -> new StairsBlock(Blocks.YELLOW_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> ORANGE_CONCRETE_STAIR = r("orange_concrete_stair", () -> new StairsBlock(Blocks.ORANGE_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> LIME_CONCRETE_STAIR = r("lime_concrete_stair", () -> new StairsBlock(Blocks.LIME_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> HASTE_ORE = r("haste_ore", () -> new OreBlock(AbstractBlock.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(3.0F, 3.0F)));
    public static final RegistryObject<Block> LUCK_ORE = r("luck_ore", () -> new OreBlock(AbstractBlock.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(3.0F, 3.0F)));
    public static final RegistryObject<Block> RED_CONCRETE_STAIR = r("red_concrete_stair", () -> new StairsBlock(Blocks.RED_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> BROWN_CONCRETE_STAIR = r("brown_concrete_stair", () -> new StairsBlock(Blocks.BROWN_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_STAIR = r("light_gray_concrete_stair", () -> new StairsBlock(Blocks.LIGHT_GRAY_CONCRETE.getDefaultState(),AbstractBlock.Properties.from(Blocks.COBBLESTONE_STAIRS)));
    public static final RegistryObject<SlabBlock> LIGHT_BLUE_CONCRETE_SLAB = r("light_blue_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> BLUE_CONCRETE_SLAB = r("blue_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> CYAN_CONCRETE_SLAB = r("cyan_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> BLACK_CONCRETE_SLAB = r("black_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> WHITE_CONCRETE_SLAB = r("white_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> BROWN_CONCRETE_SLAB = r("brown_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> RED_CONCRETE_SLAB = r("red_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> ORANGE_CONCRETE_SLAB = r("orange_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> YELLOW_CONCRETE_SLAB = r("yellow_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<Block> GARDENING_TABLE = r("gardening_table", () -> new GardeningTableBlock(AbstractBlock.Properties.from(Blocks.QUARTZ_BLOCK)));
    public static final RegistryObject<Block> CHICKEN_HUT = r("chicken_hut_1", () -> new ChickenHutBlock(1,AbstractBlock.Properties.from(Blocks.ACACIA_WOOD)));
    public static final RegistryObject<SlabBlock> PINK_CONCRETE_SLAB = r("pink_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> PURPLE_CONCRETE_SLAB = r("purple_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> MAGENTA_CONCRETE_SLAB = r("magenta_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> GRAY_CONCRETE_SLAB = r("gray_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> LIGHT_GRAY_CONCRETE_SLAB = r("light_gray_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> GREEN_CONCRETE_SLAB = r("green_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<SlabBlock> LIME_CONCRETE_SLAB = r("lime_concrete_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.WHITE_CONCRETE)));
    public static final RegistryObject<Block> TEA_BLOCK = r("tea_block", () -> new TeaBlock(AbstractBlock.Properties.create(Material.IRON).setRequiresTool().hardnessAndResistance(0.5F).setLightLevel((state) -> {
        return 1;
    }).notSolid()));
    public static final RegistryObject<Block> LIME_SAND = r("lime_sand", () -> new SandBlock(14406560,AbstractBlock.Properties.from(Blocks.SAND)));
    public static final RegistryObject<Block> ORANGE_SAND = r("orange_sand", () -> new SandBlock(14406560,AbstractBlock.Properties.from(Blocks.SAND)));
    public static final RegistryObject<Block> YELLOW_SAND = r("yellow_sand", () -> new SandBlock(14406560,AbstractBlock.Properties.from(Blocks.SAND)));
    public static final RegistryObject<Block> PINK_SAND = r("pink_sand", () -> new SandBlock(14406560,AbstractBlock.Properties.from(Blocks.SAND)));
    public static final RegistryObject<Block> PURPLE_SAND = r("purple_sand", () -> new SandBlock(14406560,AbstractBlock.Properties.from(Blocks.SAND)));
    public static final RegistryObject<Block> MOSS_BLOCK = r("moss_block", () -> new GrassBlock(AbstractBlock.Properties.from(Blocks.HAY_BLOCK).harvestTool(ToolType.HOE)));
    public static final RegistryObject<Block> MANGO_BLOCK = r("mango_block", () -> new FruitBlock(AbstractBlock.Properties.from(Blocks.DIRT).harvestTool(ToolType.HOE)));
    public static final RegistryObject<Block> MOSS_BLOCK_SLAB = r("moss_block_slab", () -> new SlabBlock(AbstractBlock.Properties.from(Blocks.DIRT).harvestTool(ToolType.HOE)));


    public static <B extends Block> RegistryObject<B> r(String name, Supplier<? extends B> supplier) {
        return BLOCKS.register(name, supplier);
    }
    public static void subscribe(IEventBus modEventBus) {
        BLOCKS.register(modEventBus);
    }

    public static Collection<RegistryObject<Block>> getBlocks() {
        return BLOCKS.getEntries();
    }


}

